

export const HEROS_GET_REQUEST = 'HEROS_GET_REQUEST';
export const HEROS_GET_SUCCESS = 'HEROS_GET_SUCCESS';
export const HEROS_GET_FAILURE = 'HEROS_GET_FAILURE';


export const HEROS_SET_SORT = 'HEROS_SET_SORT';
